### ISSUE TITLE
Extra Audio Sources

### ISSUE THREAD

**Issue by JayXT** [yomidevs/local-audio-yomichan#37]
Hello!

Is it possible to add additional sources like the ones below?
https://github.com/Ajatt-Tools/nhk_1998_pronunciations_index/archive/refs/heads/main.zip
https://github.com/Ajatt-Tools/daijisen_pronunciations_index/archive/refs/heads/main.zip
https://github.com/Ajatt-Tools/taas_pronunciations_index/archive/refs/heads/main.zip

At first sight they use the same structure inside the index.json.

**Comment by Kuuuube** [comment]
From a quick look I don't see any reason why it wouldn't work. Just add those into the addon's folder and add an entry for the new folder in the config.

**Comment by Kuuuube** [comment]
You probably should edit the config in the addons window in Anki instead. And you will need to regenerate the database.

**Comment by JayXT** [comment]
Editing the default_config.json and then regenerating the DB helped.

I've used the following entries:
```
    {
      "type": "ajt_jp",
      "id": "daijisen",
      "path": "user_files/daijisen_files",
      "display": "DJS %s"
    },
    {
      "type": "ajt_jp",
      "id": "taas",
      "path": "user_files/taas_files",
      "display": "TAAS"
    },
```
